Fix typos and update WORDLIST
epinowcast/epinowcast pull request #221
Opened 2023-04-04 13:55 UTC by Bisaloo

2023-04-04 18:12 UTC, seabbs requested changes
LGTM - thanks! Can you add a bullet to the news file on this PR and linking to it (as in the other examples) and then this is good to go.

2023-04-04 22:11 UTC, adrian-lison approved these changes

2023-04-05 09:16 UTC, seabbs requested changes
Being very fussy on the structure of the news item (we may need more info on this or move responsibility outside of PRs)

2023-04-05 09:16 UTC, seabbs commented on NEWS.md
> +- Fixed some typos in `README.md`, `NEWS.md`, the `model.Rmd` vignette and `convolution_matrix()` documentation. The `WORDLIST` used by spelling has also been updated by eliminate false positives. Se
```suggestion
- Fixed some typos in `README.md`, `NEWS.md`, the `model.Rmd` vignette and `convolution_matrix()` documentation. The `WORDLIST` used by spelling has also been updated by eliminate false positives. See #221 by @Bisaloo and reviewed by @seabbs and @adrian-lison.
```

2023-04-05 09:26 UTC, seabbs approved these changes
LGTM to me. Thanks for this 😄. I'm happy for it to be merged as and when.

2023-04-05 11:19 UTC, Bisaloo commented
An extra commit from `develop` snuck in and I don't like it. It seems like a bug from GitHub and I don't see any way to solve it. Let me try to merge #220 first and rebase and see if it solves it.

2023-04-11 10:56 UTC, merged