Add check for missing grouping variables
epinowcast/epinowcast pull request #295
Opened 2023-08-01 15:45 UTC by adrian-lison

## Description

This PR closes #294 by adding a clear error message when the data is stratified by more grouping variables than stated in the `by` argument of `enw_preprocess_data`. The user can then either add more variables to `by`, or aggregate the data by themselves beforehand. Maybe we should also offer a special preprocessing function for the latter in `epinowcast`?

The alternative would be to try to handle this gracefully, but I think we would end up chasing errors in the downstream preprocessing functions (the cryptic error occured in `add_max_reported`, which is quite early in the whole preprocessing pipeline, more errors would like arise after this was resolved). The above solution therefore seems cleanest to me. Alternative opinions welcome of course.

## Checklist

- [ ] My PR is based on a package issue and I have explicitly linked it.
- [ ] I have included the target issue or issues in the PR title in the for Issue(s) *issue-numbers*: PR title
- [ ] I have read the [contribution guidelines](https://github.com/epinowcast/epinowcast/blob/main/CONTRIBUTING.md).
- [ ] I have tested my changes locally.
- [ ] I have updated the documentation if required.
- [ ] My code follows the established coding standards.
- [ ] I have added a news item linked to this PR.
- [ ] I have updated the package development version by one increment in both `NEWS.md` and the `DESCRIPTION`.
- [ ] I have reviewed CI checks for this PR and addressed them as far as I am able.

2023-08-02 09:03 UTC, seabbs requested changes
Code implementation looks good. Need to fix some linting issues and add a test showing the edge case is fixed.

2023-08-02 09:06 UTC, seabbs commented
Nice stuff!

>  The user can then either add more variables to by, or aggregate the data by themselves beforehand. Maybe we should also offer a special preprocessing function for the latter in epinowcast?

Yes agree. 

> but I think we would end up chasing errors in the downstream preprocessing functions 

Agree

The test failure is coming from the fact that when we test we don't enforce "reference_date" or "report_date" to be present. We could either enforce this and change the tests as expected or (my preference) group on these variables only if they are present. If not documented then the fact we are doing this probably should be.

See: https://github.com/epinowcast/epinowcast/blob/49020b8a08ec9b38a45abb07a0fb28eaa62932e7/R/preprocess.R#L288

2023-08-03 13:04 UTC, seabbs commented
This felt like maybe it should be its own function vs a side effect when I started to look at the issues we were having with edge cases. What do you think?

I've implemented this hence why now passing checks. Happy to revert.

2023-08-03 16:37 UTC, seabbs approved these changes
LGTM. From my side, this looks good but I think given the changes I've made @adrian-lison you should do your own review. Happy for this to be merged as is or to do another round of review after more changes.

2023-08-09 17:05 UTC, adrian-lison commented
Looks good to me too. I made an issue (#304) for the aggregation function. Ready to merge. But how can I self-review?

2023-08-10 09:17 UTC, seabbs submitted a review, later dismissed
LGTM 🥳  (it just needs a review from not the person who made the PR I think and old reviews get dismissed when new commits come in)

2023-08-10 09:42 UTC, seabbs reviewed
Somehow the check inside `enw_assign_group()` snuck back in. I have removed and so now all works as expected.

2023-08-10 09:43 UTC, seabbs approved these changes

2023-08-10 16:13 UTC, seabbs approved these changes

2023-08-10 17:04 UTC, seabbs approved these changes

2023-08-10 17:57 UTC, merged